Task 25 linkedin auth front end / back end
fe-team-itechart/project-x-server pull request #26
Opened 2019-09-10 14:18 UTC by melonholy

2019-09-11 08:24 UTC, OlegPanasyuk approved these changes

2019-09-11 12:05 UTC, slavasgod requested changes

2019-09-11 12:05 UTC, slavasgod commented on swaggerDef.js
> +  apis: ['api/**/*.js'],
Move this file to config folder, it's a swagger config.

2019-09-12 13:28 UTC, slavasgod approved these changes

2019-09-13 10:51 UTC, merged