Task 8 profile back end
fe-team-itechart/project-x-server pull request #27
Opened 2019-09-16 09:44 UTC by universezzz

2019-09-16 12:16 UTC, OlegPanasyuk approved these changes

2019-09-16 15:52 UTC, melonholy requested changes

2019-09-16 15:52 UTC, melonholy commented on api/controllers/profile.js
> +const { isEmpty } = require('lodash');
import native libraries at the beginning

2019-09-16 15:52 UTC, melonholy commented on api/services/profile.js
> +  const { id } = jwt_decode(token);
if future we need to write middleware for token decoding and we are using `jsonwebtoken` library for working with jwt tokens

2019-09-16 15:52 UTC, melonholy commented on package.json
> +    "jwt-decode": "^2.2.0",
we already have `jsonwebtoken` as a main library for working with jwt tokens

2019-09-16 15:52 UTC, melonholy commented on api/services/profile.js
> +  const { id } = jwt_decode(req.headers.token);
comment above

2019-09-17 10:22 UTC, universezzz commented on package.json
> +    "jwt-decode": "^2.2.0",
has removed.

2019-09-17 10:22 UTC, universezzz commented on api/services/profile.js
> +  const { id } = jwt_decode(req.headers.token);
has fixed

2019-09-17 10:22 UTC, universezzz commented on api/services/profile.js
> +  const { id } = jwt_decode(token);
has fixed

2019-09-17 10:22 UTC, universezzz commented on api/controllers/profile.js
> +const { isEmpty } = require('lodash');
has fixed

2019-09-18 07:30 UTC, slavasgod approved these changes

2019-09-18 07:32 UTC, merged